DROP TABLE IF EXISTS posts;

CREATE VIRTUAL TABLE posts USING fts4 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    tags TEXT NOT NULL,
    description TEXT NOT NULL,
    content TEXT NOT NULL,
    wordcount INTEGER
);